@set PATH=c:\gcc850\bin;c:\gcc850\lib;C:\Gcc850\source\firmware_sau70000

rem C:\gvd_win\bin\gvd.exe  --debugger c:\gcc850\bin\gdb.exe sau7000.elf

rem c:\gps\bin\gps.exe --debug="sau7000.elf" --debugger c:\gcc850\bin\gdb.exe

rem C:\GNAT\2011\bin\gps.exe  --debug="sg2.out" --debugger c:\gcc850\bin\gdb.exe
C:\GNAT\2011\bin\gps.exe --debug="sau7000.elf" --debugger c:\gcc850\bin\gdb.exe

rem c:\gps-1.2.2\bin\gps.exe --debug="sau7000.elf" --debugger c:\gcc850\bin\gdb.exe
rem c:\gcc850\bin\gdb.exe 

